### ISSUE TITLE
Errors in JSON parsing

### ISSUE THREAD

**Issue by emning** [domeneshop/python-domeneshop#1]
Hi there!

We tried to use the library in combination with the Certbot plugin, but kept getting error messages like the following:

````
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/certbot/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/local/lib/python3.5/dist-packages/certbot/plugins/dns_common.py", line 58, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/local/lib/python3.5/dist-packages/certbot_dns_domeneshop/dns_domeneshop.py", line 68, in _perform
    provider_domains = client.get_domains()
  File "/usr/local/lib/python3.5/dist-packages/domeneshop/client.py", line 73, in get_domains
    domains = json.loads(resp.data)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
````

We got it working by adding a ````.decode()```` before every call to ````json.loads()````, see this commit for details: https://github.com/emning/python-domeneshop/commit/0c32f042c65ee3bd31128801d6e39ce131b5f658

I didn't want to create a pull request, as I'm no unicode expert, but can do so if you'd like. However, to do this properly we should probably also decode with the charset specified by the HTTP headers, which would require a bit more work.

Also, I'm having a bit of trouble seeing how this code could ever have worked at all, as all the docs I find say that urllib3 will always return bytes. Presumably something must have changed in some library along the way, so figuring that out before patching is probably a good idea.

Platform:
* Ubuntu 16.04.6
* Python 3.5.2
* certbot==0.40.1
* domeneshop==0.4.1
* certbot-dns-domeneshop==0.2.6

**Comment by eirikrye** [comment]
Hi,

Thanks for reporting this. Python apparently changed their `json` API with Python 3.6+ to allow byte strings as input for `json.loads`. We will publish a fix for this very soon, and implement a more rigorous test suite for future releases as the API matures.

**Comment by eirikrye** [comment]
Version 0.4.2 is now released to resolve this issue, along with `certbot-dns-domeneshop` version 0.2.7 which requires this new version.

Feel free to reopen if you are still experiencing issues.

**Comment by emning** [comment]
Thank you for the incredibly quick response!

Confirmed OK for us with the new versions.
