### ISSUE TITLE
Wrong signature for create_record? 

### ISSUE THREAD

**Issue by DoRullings** [domeneshop/python-domeneshop#3]
Just a minor issue, but the **create_record** method  in the class **Client** requires a dict ('record') as the second parameter, but the signature is: 

`def create_record(self, domain_id: int, record: int) -> int:`

while it should been:

`def create_record(self, domain_id: int, record: dict) -> int:`

**Comment by eirikrye** [comment]
Fixed in ba44eaa1debf99b9a16a31cf13f0234e2090d396.
